DROP TABLE IF EXISTS creators CASCADE;
DROP TABLE IF EXISTS voters CASCADE;
DROP TABLE IF EXISTS choices CASCADE;
DROP TABLE IF EXISTS polls CASCADE;

CREATE TABLE creators (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE voters (
  id SERIAL PRIMARY KEY NOT NULL,
  choice_id INTEGER REFERENCES choices(id) ON DELETE CASCADE
);

CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  choice_rank INTEGER NOT NULL
);

CREATE TABLE polls(
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES creators(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  admin_link VARCHAR(255) NOT NULL,
  submission_link VARCHAR(255) NOT NULL
);